# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 08d6262a-md-taco
  namespace: 08d6262a
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: tks
